version: '3.1'

services:
  lti:
    build:
      context: .
      args:
        - "REQUIREMENTS=${REQUIREMENTS}"
    volumes:
      - .:/code
    ports:
      - "9001:9001"
    env_file:
      - .env
